name: paraText
channels:
  - defaults
dependencies:
  - pycodestyle
  - numpy
  - python=3.10
#  - tk
#  - tk-tools
#  - apt-get
#  - apt-get:
#      python3-tk
#  - pip:
#      - tk-tools
##      - tkinter
